[package]
name = "ag-harness"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[[test]]
name = "e2e"
path = "tests/e2e/main.rs"
test = false
bench = false

[[test]]
name = "benchmark"
path = "tests/benchmark/main.rs"
test = false
bench = false
harness = false

[dependencies]
async-trait.workspace = true
jsonschema.workspace = true
opentelemetry.workspace = true
reqwest.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["arbitrary_precision"] }
sqlx.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
mockall.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry-proto.workspace = true
opentelemetry_sdk = { workspace = true, features = ["testing"] }
prost.workspace = true
wiremock.workspace = true

[lints]
workspace = true
