[package]
name = "ag-git"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[features]
test-utils = ["dep:mockall"]

[dependencies]
mockall = { workspace = true, optional = true }
rustix.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
mockall.workspace = true

[lints]
workspace = true
