use ratatui::Frame;
use ratatui::layout::Rect;
use ratatui::style::Style;
use ratatui::text::{Line, Span};
use ratatui::widgets::{Block, Borders, Paragraph};
use serde_json;

use crate::domain::session::{Session, SessionFollowUpTask, Status};
use crate::icon::Icon;
use crate::infra::agent::protocol::AgentResponseSummary;
use crate::ui::markdown::render_markdown;
use crate::ui::state::app_mode::DoneSessionOutputMode;
use crate::ui::{Component, style, text_util};

const USER_PROMPT_PREFIX: &str = " › ";
const USER_PROMPT_CONTINUATION_PREFIX: &str = "   ";
const CLARIFICATION_HEADER_LINE: &str = " › Clarifications:";
/// Markdown heading used for synthetic follow-up-task rendering.
const FOLLOW_UP_TASK_HEADER: &str = "Follow-Up Tasks [Preview]";
const TRANSCRIPT_FOOTER_PREFIXES: &[&str] = &["[Commit]", "[Commit Error]"];

/// Session chat output panel renderer.
pub struct SessionOutput<'a> {
    active_progress: Option<&'a str>,
    /// Selected panel content for the session output panel.
    done_session_output_mode: DoneSessionOutputMode,
    review_status_message: Option<&'a str>,
    review_text: Option<&'a str>,
    scroll_offset: Option<u16>,
    session: &'a Session,
}

impl<'a> SessionOutput<'a> {
    const DEFAULT_SUMMARY_TEXT: &'static str = "No changes";

    /// Creates a new session output component.
    pub fn new(session: &'a Session) -> Self {
        Self {
            active_progress: None,
            done_session_output_mode: DoneSessionOutputMode::Summary,
            review_status_message: None,
            review_text: None,
            scroll_offset: None,
            session,
        }
    }

    /// Sets transient progress text rendered in the loader row.
    #[must_use]
    pub fn active_progress(mut self, active_progress: &'a str) -> Self {
        self.active_progress = Some(active_progress);
        self
    }

    /// Sets the output display mode for completed sessions.
    #[must_use]
    pub fn done_session_output_mode(mut self, mode: DoneSessionOutputMode) -> Self {
        self.done_session_output_mode = mode;
        self
    }

    /// Sets the review status message rendered when review text is not
    /// available.
    #[must_use]
    pub fn review_status_message(mut self, status_message: Option<&'a str>) -> Self {
        self.review_status_message = status_message;
        self
    }

    /// Sets review text generated by an agent.
    #[must_use]
    pub fn review_text(mut self, review_text: Option<&'a str>) -> Self {
        self.review_text = review_text;
        self
    }

    /// Sets the vertical scroll offset.
    #[must_use]
    pub fn scroll_offset(mut self, offset: u16) -> Self {
        self.scroll_offset = Some(offset);
        self
    }

    /// Returns the rendered output line count for chat content at a given
    /// width.
    ///
    /// This mirrors the exact wrapping and footer line rules used during
    /// rendering so scroll math can stay in sync with what users see.
    pub(crate) fn rendered_line_count(
        session: &Session,
        output_width: u16,
        done_session_output_mode: DoneSessionOutputMode,
        review_status_message: Option<&str>,
        review_text: Option<&str>,
        active_progress: Option<&str>,
    ) -> u16 {
        let output_area = Rect::new(0, 0, output_width, 0);
        let lines = Self::output_lines(
            session,
            output_area,
            session.status,
            done_session_output_mode,
            review_status_message,
            review_text,
            active_progress,
        );

        u16::try_from(lines.len()).unwrap_or(u16::MAX)
    }

    /// Builds rendered markdown lines and contextual status/help rows for the
    /// current session state.
    ///
    /// `Status::Done` includes an inline `t` toggle hint that switches between
    /// summary and full output views. Active statuses append only the generic
    /// loader row so transcript text stays stable until the turn completes.
    /// Wrapping width follows the configured output panel borders so line
    /// metrics stay in sync with rendered content. Trailing commit notices are
    /// rendered after follow-up tasks so auto-commit updates do not jump above
    /// the assistant's structured footer section. Review mode suppresses
    /// transcript-only follow-up tasks because the panel is showing review
    /// assist content rather than the chat transcript.
    fn output_lines(
        session: &Session,
        output_area: Rect,
        status: Status,
        done_session_output_mode: DoneSessionOutputMode,
        review_status_message: Option<&str>,
        review_text: Option<&str>,
        active_progress: Option<&str>,
    ) -> Vec<Line<'static>> {
        let output_text = Self::output_text(
            session,
            status,
            done_session_output_mode,
            review_status_message,
            review_text,
        );
        let output_text = Self::output_text_with_spaced_user_input(&output_text);
        let (output_text, trailing_footer_text) =
            text_util::split_trailing_line_block(&output_text, TRANSCRIPT_FOOTER_PREFIXES);
        let inner_width = output_area
            .width
            .saturating_sub(Self::output_horizontal_border_width())
            as usize;
        let mut lines = render_markdown(&output_text, inner_width);
        if Self::shows_follow_up_tasks(done_session_output_mode) {
            Self::append_follow_up_task_lines(&mut lines, &session.follow_up_tasks, inner_width);
        }
        Self::append_transcript_footer_lines(&mut lines, trailing_footer_text, inner_width);

        if matches!(
            status,
            Status::InProgress | Status::Queued | Status::Rebasing | Status::Merging
        ) {
            while lines.last().is_some_and(|line| line.width() == 0) {
                lines.pop();
            }

            lines.push(Line::from(""));

            let status_icon = Self::status_icon(status);
            let status_message = Self::status_message(status, active_progress);
            lines.push(Line::from(vec![Span::styled(
                format!("{status_icon} {status_message}"),
                Style::default().fg(style::status_color(status)),
            )]));
        } else if status == Status::Done {
            lines.push(Line::from(""));
            lines.push(Self::done_output_toggle_line(done_session_output_mode));
            lines.push(Line::from(""));
        } else {
            lines.push(Line::from(""));
        }

        lines
    }

    /// Returns horizontal width consumed by the output panel border.
    fn output_horizontal_border_width() -> u16 {
        let output_panel_borders = Self::output_panel_borders();
        let left_border_width = u16::from(output_panel_borders.intersects(Borders::LEFT));
        let right_border_width = u16::from(output_panel_borders.intersects(Borders::RIGHT));

        left_border_width + right_border_width
    }

    /// Returns borders used for the session output panel.
    ///
    /// Vertical borders stay hidden so terminal copy/select flows do not pick
    /// up extra gutter characters.
    fn output_panel_borders() -> Borders {
        Borders::TOP | Borders::BOTTOM
    }

    /// Returns the border style used for the session output frame.
    fn output_panel_border_style(status: Status) -> Style {
        Style::default().fg(style::status_color(status))
    }

    /// Returns the inline shortcut hint for toggling done-session content.
    fn done_output_toggle_line(done_session_output_mode: DoneSessionOutputMode) -> Line<'static> {
        let toggle_target = match done_session_output_mode {
            DoneSessionOutputMode::Summary => "output",
            DoneSessionOutputMode::Output | DoneSessionOutputMode::Review => "summary",
        };

        Line::from(vec![Span::styled(
            format!("Press t to switch to {toggle_target}."),
            Style::default().fg(style::palette::TEXT_SUBTLE),
        )])
    }

    /// Returns the source text shown in the output panel for the current
    /// status and done-session display mode.
    ///
    /// Summary markdown is shown only for `Done` sessions after it has been
    /// persisted. Active and canceled sessions render transcript output only.
    fn output_text(
        session: &Session,
        status: Status,
        done_session_output_mode: DoneSessionOutputMode,
        review_status_message: Option<&str>,
        review_text: Option<&str>,
    ) -> String {
        if done_session_output_mode == DoneSessionOutputMode::Review {
            if let Some(review_text) = review_text {
                return review_text.to_string();
            }

            if let Some(review_status_message) = review_status_message {
                return review_status_message.to_string();
            }

            return "Review is not available.".to_string();
        }

        match status {
            Status::Done if done_session_output_mode == DoneSessionOutputMode::Summary => {
                return Self::render_summary_text(Self::session_summary_text(session));
            }
            Status::Canceled => {
                return session.output.clone();
            }
            Status::Review
            | Status::Question
            | Status::New
            | Status::Done
            | Status::InProgress
            | Status::Queued
            | Status::Rebasing
            | Status::Merging => {}
        }

        session.output.clone()
    }

    /// Returns the persisted raw summary payload or plain-text fallback.
    fn session_summary_text(session: &Session) -> &str {
        session
            .summary
            .as_deref()
            .map(str::trim)
            .filter(|summary| !summary.is_empty())
            .unwrap_or("")
    }

    /// Renders one persisted summary payload into markdown for display.
    fn render_summary_text(summary_text: &str) -> String {
        let trimmed_summary = summary_text.trim();
        if let Ok(summary_payload) = serde_json::from_str::<AgentResponseSummary>(trimmed_summary) {
            return format!(
                "## Change Summary\n### Current Turn\n{}\n\n### Session Changes\n{}",
                Self::summary_section_text(&summary_payload.turn),
                Self::summary_section_text(&summary_payload.session)
            );
        }

        if !trimmed_summary.is_empty() {
            return trimmed_summary.to_string();
        }

        format!(
            "## Change Summary\n### Current Turn\n{}\n\n### Session Changes\n{}",
            Self::DEFAULT_SUMMARY_TEXT,
            Self::DEFAULT_SUMMARY_TEXT
        )
    }

    /// Returns one rendered summary section value, falling back to
    /// `No changes` when the persisted value is blank.
    fn summary_section_text(summary_text: &str) -> &str {
        let trimmed_summary = summary_text.trim();
        if trimmed_summary.is_empty() {
            return Self::DEFAULT_SUMMARY_TEXT;
        }

        trimmed_summary
    }

    /// Returns whether the output panel should append transcript-scoped
    /// follow-up tasks for the selected display mode.
    fn shows_follow_up_tasks(done_session_output_mode: DoneSessionOutputMode) -> bool {
        done_session_output_mode != DoneSessionOutputMode::Review
    }

    /// Appends a rendered follow-up-task section without mutating persisted
    /// transcript or summary text.
    ///
    /// The section header includes a preview badge so users can distinguish
    /// generated follow-up tasks from transcript content.
    fn append_follow_up_task_lines(
        lines: &mut Vec<Line<'static>>,
        follow_up_tasks: &[SessionFollowUpTask],
        inner_width: usize,
    ) {
        if follow_up_tasks.is_empty() {
            return;
        }

        let follow_up_task_markdown = format!(
            "## {FOLLOW_UP_TASK_HEADER}\n{}",
            follow_up_tasks
                .iter()
                .map(|follow_up_task| format!("- {}", follow_up_task.text))
                .collect::<Vec<_>>()
                .join("\n")
        );
        Self::append_markdown_lines(lines, &follow_up_task_markdown, inner_width);
    }

    /// Appends one trailing transcript footer after synthetic follow-up-task
    /// content when a known footer block is present.
    fn append_transcript_footer_lines(
        lines: &mut Vec<Line<'static>>,
        trailing_footer_text: Option<&str>,
        inner_width: usize,
    ) {
        let Some(trailing_footer_text) = trailing_footer_text else {
            return;
        };

        Self::append_markdown_lines(lines, trailing_footer_text, inner_width);
    }

    /// Appends rendered markdown with one blank separator while trimming any
    /// existing trailing blank lines from `lines`.
    fn append_markdown_lines(lines: &mut Vec<Line<'static>>, markdown: &str, inner_width: usize) {
        let mut rendered_lines = render_markdown(markdown, inner_width);
        if rendered_lines.is_empty() {
            return;
        }

        while lines.last().is_some_and(|line| line.width() == 0) {
            lines.pop();
        }

        if !lines.is_empty() {
            lines.push(Line::from(""));
        }

        lines.append(&mut rendered_lines);
    }

    /// Adds visual spacing around user prompt blocks while preserving pasted
    /// multiline prompts as one contiguous message.
    ///
    /// Clarification replies receive one extra spacer row between numbered
    /// question/answer groups so the block scans faster than plain prompt
    /// text.
    fn output_text_with_spaced_user_input(output_text: &str) -> String {
        let raw_lines = output_text.split('\n').collect::<Vec<_>>();
        let mut formatted_lines = Vec::with_capacity(raw_lines.len());
        let mut line_index = 0;

        while line_index < raw_lines.len() {
            let line = raw_lines[line_index];
            if !line.starts_with(USER_PROMPT_PREFIX) {
                formatted_lines.push(line.to_string());
                line_index += 1;

                continue;
            }

            if formatted_lines
                .last()
                .is_some_and(|item: &String| !item.is_empty())
            {
                formatted_lines.push(String::new());
            }

            let block_end_index = Self::user_prompt_block_end_index(&raw_lines, line_index);
            formatted_lines.extend(Self::format_prompt_block_lines(
                &raw_lines[line_index..=block_end_index],
            ));
            line_index = block_end_index + 1;

            let next_line_is_empty = raw_lines
                .get(line_index)
                .is_none_or(|next_line| next_line.is_empty());
            if !next_line_is_empty {
                formatted_lines.push(String::new());
            }
        }

        formatted_lines.join("\n")
    }

    /// Formats one prompt block and inserts intra-block separators for
    /// clarification question groups.
    fn format_prompt_block_lines(raw_block_lines: &[&str]) -> Vec<String> {
        if !Self::is_clarification_prompt_block(raw_block_lines) {
            return raw_block_lines.iter().map(ToString::to_string).collect();
        }

        let mut formatted_block_lines = Vec::with_capacity(raw_block_lines.len() + 2);
        for (block_line_index, raw_block_line) in raw_block_lines.iter().enumerate() {
            if block_line_index > 0 && Self::is_clarification_question_line(raw_block_line) {
                formatted_block_lines.push(USER_PROMPT_CONTINUATION_PREFIX.to_string());
            }

            formatted_block_lines.push((*raw_block_line).to_string());
        }

        formatted_block_lines
    }

    /// Returns true when the prompt block is the generated clarifications
    /// payload.
    fn is_clarification_prompt_block(raw_block_lines: &[&str]) -> bool {
        raw_block_lines
            .first()
            .is_some_and(|line| line.trim_end() == CLARIFICATION_HEADER_LINE)
    }

    /// Returns true for numbered clarification question rows like
    /// `   1. Q: Need tests?`.
    fn is_clarification_question_line(raw_block_line: &str) -> bool {
        let Some(line_without_prefix) =
            raw_block_line.strip_prefix(USER_PROMPT_CONTINUATION_PREFIX)
        else {
            return false;
        };
        let trimmed_line = line_without_prefix.trim_start();
        let digit_count = trimmed_line
            .chars()
            .take_while(char::is_ascii_digit)
            .count();
        if digit_count == 0 {
            return false;
        }

        let (_, suffix) = trimmed_line.split_at(digit_count);

        suffix.starts_with(". Q: ")
    }

    /// Returns the final non-empty line index for a user prompt block that
    /// starts at `start_index`.
    fn user_prompt_block_end_index(raw_lines: &[&str], start_index: usize) -> usize {
        let mut candidate_index = start_index + 1;

        while candidate_index < raw_lines.len() {
            let candidate_line = raw_lines[candidate_index];
            if candidate_line.is_empty() || candidate_line.starts_with(USER_PROMPT_PREFIX) {
                break;
            }

            candidate_index += 1;
        }

        if raw_lines
            .get(candidate_index)
            .is_some_and(|candidate_line| candidate_line.is_empty())
        {
            return candidate_index.saturating_sub(1).max(start_index);
        }

        start_index
    }

    /// Returns the loader label for active session states.
    fn status_message(status: Status, active_progress: Option<&str>) -> String {
        match status {
            Status::InProgress => active_progress
                .map(str::trim)
                .filter(|progress| !progress.is_empty())
                .map_or_else(
                    || "Working...".to_string(),
                    |progress| format!("Working... {progress}"),
                ),
            Status::Queued => "Waiting in merge queue...".to_string(),
            Status::Rebasing => "Rebasing...".to_string(),
            Status::Merging => "Merging...".to_string(),
            Status::New | Status::Review | Status::Question | Status::Done | Status::Canceled => {
                String::new()
            }
        }
    }

    /// Returns the status indicator icon used for inline status messages.
    fn status_icon(status: Status) -> Icon {
        match status {
            Status::InProgress | Status::Rebasing | Status::Merging => Icon::current_spinner(),
            Status::Queued
            | Status::New
            | Status::Review
            | Status::Question
            | Status::Done
            | Status::Canceled => Icon::Pending,
        }
    }

    fn final_scroll_offset(&self, output_area: Rect, line_count: usize) -> u16 {
        if let Some(scroll_offset) = self.scroll_offset {
            return scroll_offset;
        }

        let inner_height = output_area.height.saturating_sub(2) as usize;

        u16::try_from(line_count.saturating_sub(inner_height)).unwrap_or(u16::MAX)
    }
}

impl Component for SessionOutput<'_> {
    /// Renders bordered output content for the active session.
    ///
    /// Session status/title headers are rendered by the page layer so this
    /// component keeps the output border title-free.
    fn render(&self, f: &mut Frame, output_area: Rect) {
        let status = self.session.status;
        let lines = Self::output_lines(
            self.session,
            output_area,
            status,
            self.done_session_output_mode,
            self.review_status_message,
            self.review_text,
            self.active_progress,
        );
        let final_scroll = self.final_scroll_offset(output_area, lines.len());

        let paragraph = Paragraph::new(lines)
            .block(
                Block::default()
                    .borders(Self::output_panel_borders())
                    .border_style(Self::output_panel_border_style(status)),
            )
            .scroll((final_scroll, 0));

        f.render_widget(paragraph, output_area);
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use ratatui::style::Modifier;
    use serde_json;

    use super::*;
    use crate::agent::AgentModel;
    use crate::domain::session::{SessionSize, SessionStats};
    use crate::infra::agent::protocol::AgentResponseSummary;

    fn summary_fixture() -> String {
        serde_json::to_string(&AgentResponseSummary {
            turn: "- Added the structured protocol summary.".to_string(),
            session: "- Session output now renders persisted summary markdown.".to_string(),
        })
        .expect("summary fixture should serialize")
    }

    fn session_fixture() -> Session {
        Session {
            base_branch: "main".to_string(),
            created_at: 0,
            folder: PathBuf::new(),
            follow_up_tasks: Vec::new(),
            id: "session-id".to_string(),
            in_progress_started_at: None,
            in_progress_total_seconds: 0,
            model: AgentModel::Gemini3FlashPreview,
            output: String::new(),
            project_name: "project".to_string(),
            prompt: String::new(),
            published_upstream_ref: None,
            questions: Vec::new(),
            review_request: None,
            size: SessionSize::Xs,
            stats: SessionStats::default(),
            status: Status::New,
            summary: None,
            title: None,
            updated_at: 0,
        }
    }

    fn buffer_text(buffer: &ratatui::buffer::Buffer) -> String {
        buffer
            .content()
            .iter()
            .map(ratatui::buffer::Cell::symbol)
            .collect()
    }

    #[test]
    fn test_rendered_line_count_counts_wrapped_content() {
        // Arrange
        let mut session = session_fixture();
        session.output = "word ".repeat(40);
        let raw_line_count = u16::try_from(session.output.lines().count()).unwrap_or(u16::MAX);

        // Act
        let rendered_line_count = SessionOutput::rendered_line_count(
            &session,
            20,
            DoneSessionOutputMode::Summary,
            None,
            None,
            None,
        );

        // Assert
        assert!(rendered_line_count > raw_line_count);
    }

    #[test]
    fn test_output_lines_uses_summary_for_done_session() {
        // Arrange
        let mut session = session_fixture();
        session.output = "streamed output".to_string();
        session.summary = Some(summary_fixture());
        session.status = Status::Done;

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 5),
            session.status,
            DoneSessionOutputMode::Summary,
            None,
            None,
            None,
        );
        let text = lines
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n");

        // Assert
        assert!(text.contains("Added the structured protocol summary."));
        assert!(text.contains("Session output now renders persisted summary markdown."));
        assert!(!text.contains("streamed output"));
    }

    #[test]
    /// Ensures rendered output shows follow-up tasks without requiring them
    /// to be appended to the persisted transcript string.
    fn test_output_lines_append_follow_up_task_section_without_mutating_output() {
        // Arrange
        let mut session = session_fixture();
        session.output = "streamed output".to_string();
        session.follow_up_tasks = vec![
            SessionFollowUpTask {
                id: 1,
                text: "Document the new shortcut.".to_string(),
            },
            SessionFollowUpTask {
                id: 2,
                text: "Add a regression test.".to_string(),
            },
        ];

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 8),
            session.status,
            DoneSessionOutputMode::Summary,
            None,
            None,
            None,
        );
        let text = lines
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n");

        // Assert
        assert_eq!(session.output, "streamed output");
        assert!(text.contains("streamed output"));
        assert!(text.contains(FOLLOW_UP_TASK_HEADER));
        assert!(text.contains("Document the new shortcut."));
        assert!(text.contains("Add a regression test."));
    }

    #[test]
    fn test_output_lines_renders_trailing_commit_footer_after_follow_up_tasks() {
        // Arrange
        let mut session = session_fixture();
        session.output =
            "Implemented the change.\n\n[Commit] committed with hash `abc1234`\n".to_string();
        session.follow_up_tasks = vec![SessionFollowUpTask {
            id: 1,
            text: "Run a broader regression pass.".to_string(),
        }];

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 8),
            session.status,
            DoneSessionOutputMode::Summary,
            None,
            None,
            None,
        );
        let text = lines
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n");
        let follow_up_index = text
            .find(FOLLOW_UP_TASK_HEADER)
            .expect("follow-up task header should be rendered");
        let commit_index = text
            .find("[Commit] committed with hash abc1234")
            .expect("commit footer should be rendered");

        // Assert
        assert!(text.contains("Implemented the change."));
        assert!(text.contains("Run a broader regression pass."));
        assert!(follow_up_index < commit_index);
    }

    #[test]
    fn test_output_lines_uses_streamed_output_for_done_session_in_output_mode() {
        // Arrange
        let mut session = session_fixture();
        session.output = "streamed output".to_string();
        session.summary = Some(summary_fixture());
        session.status = Status::Done;

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 5),
            session.status,
            DoneSessionOutputMode::Output,
            None,
            None,
            None,
        );
        let text = lines
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n");

        // Assert
        assert!(!text.contains("Added the structured protocol summary."));
        assert!(text.contains("streamed output"));
    }

    #[test]
    fn test_output_lines_review_session_uses_transcript_only() {
        // Arrange
        let mut session = session_fixture();
        session.output = "implemented the feature".to_string();
        session.summary = Some(summary_fixture());
        session.status = Status::Review;

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 5),
            session.status,
            DoneSessionOutputMode::Summary,
            None,
            None,
            None,
        );
        let text = lines
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n");

        // Assert
        assert!(text.contains("implemented the feature"));
        assert!(!text.contains("Added the structured protocol summary."));
        assert!(!text.contains("Session output now renders persisted summary markdown."));
    }

    #[test]
    fn test_output_lines_review_session_without_summary_keeps_transcript_only() {
        // Arrange
        let mut session = session_fixture();
        session.output = "implemented the feature".to_string();
        session.status = Status::Review;

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 5),
            session.status,
            DoneSessionOutputMode::Summary,
            None,
            None,
            None,
        );
        let text = lines
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n");

        // Assert
        assert!(text.contains("implemented the feature"));
        assert!(!text.contains("No changes"));
        assert!(!text.contains("Current Turn"));
        assert!(!text.contains("Session Changes"));
    }

    #[test]
    fn test_render_summary_text_uses_plain_text_fallback_for_non_protocol_summary() {
        // Arrange / Act
        let rendered_summary = SessionOutput::render_summary_text("plain summary");

        // Assert
        assert_eq!(rendered_summary, "plain summary");
    }

    #[test]
    fn test_output_lines_done_summary_mode_shows_output_toggle_action() {
        // Arrange
        let mut session = session_fixture();
        session.output = "streamed output".to_string();
        session.summary = Some(summary_fixture());
        session.status = Status::Done;

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 5),
            session.status,
            DoneSessionOutputMode::Summary,
            None,
            None,
            None,
        );
        let text = lines
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n");

        // Assert
        assert!(text.contains("Press t to switch to output."));
    }

    #[test]
    fn test_output_lines_done_output_mode_shows_summary_toggle_action() {
        // Arrange
        let mut session = session_fixture();
        session.output = "streamed output".to_string();
        session.summary = Some(summary_fixture());
        session.status = Status::Done;

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 5),
            session.status,
            DoneSessionOutputMode::Output,
            None,
            None,
            None,
        );
        let text = lines
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n");

        // Assert
        assert!(text.contains("Press t to switch to summary."));
    }

    #[test]
    fn test_output_lines_review_mode_shows_unavailable_message_without_assisted_text() {
        // Arrange
        let mut session = session_fixture();
        session.status = Status::Review;

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 5),
            session.status,
            DoneSessionOutputMode::Review,
            None,
            None,
            None,
        );
        let text = lines
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n");

        // Assert
        assert!(text.contains("Review is not available."));
    }

    #[test]
    fn test_output_lines_done_review_mode_shows_summary_toggle_action() {
        // Arrange
        let mut session = session_fixture();
        session.status = Status::Done;

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 5),
            session.status,
            DoneSessionOutputMode::Review,
            None,
            None,
            None,
        );
        let text = lines
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n");

        // Assert
        assert!(text.contains("Press t to switch to summary."));
    }

    #[test]
    fn test_output_lines_review_mode_prefers_assisted_text() {
        // Arrange
        let mut session = session_fixture();
        session.status = Status::Review;
        let assisted_text = "## Review\n\n- Assisted insight";

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 5),
            session.status,
            DoneSessionOutputMode::Review,
            Some("Preparing review with agent help..."),
            Some(assisted_text),
            None,
        );
        let text = lines
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n");

        // Assert
        assert!(text.contains("Assisted insight"));
        assert!(!text.contains("Preparing review with agent help..."));
    }

    #[test]
    fn test_output_lines_review_mode_shows_status_message() {
        // Arrange
        let mut session = session_fixture();
        session.status = Status::Review;

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 5),
            session.status,
            DoneSessionOutputMode::Review,
            Some("Preparing review with agent help..."),
            None,
            None,
        );
        let text = lines
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n");

        // Assert
        assert!(text.contains("Preparing review with agent help..."));
        assert!(!text.contains("Review is not available."));
    }

    #[test]
    fn test_output_lines_review_mode_hides_follow_up_tasks() {
        // Arrange
        let mut session = session_fixture();
        session.status = Status::Review;
        session.follow_up_tasks = vec![SessionFollowUpTask {
            id: 1,
            text: "Run cargo test -q.".to_string(),
        }];

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 5),
            session.status,
            DoneSessionOutputMode::Review,
            Some("Preparing review with agent help..."),
            None,
            None,
        );
        let text = lines
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n");

        // Assert
        assert!(text.contains("Preparing review with agent help..."));
        assert!(!text.contains(FOLLOW_UP_TASK_HEADER));
        assert!(!text.contains("Run cargo test -q."));
    }

    #[test]
    fn test_output_lines_uses_transcript_for_canceled_session() {
        // Arrange
        let mut session = session_fixture();
        session.output = "streamed output".to_string();
        session.summary = Some(summary_fixture());
        session.status = Status::Canceled;

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 5),
            session.status,
            DoneSessionOutputMode::Summary,
            None,
            None,
            None,
        );
        let text = lines
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n");

        // Assert
        assert!(!text.contains("Added the structured protocol summary."));
        assert!(text.contains("streamed output"));
    }

    #[test]
    fn test_output_lines_render_user_prompt_with_cyan_bold_styling() {
        // Arrange
        let mut session = session_fixture();
        session.output = " › /model gemini".to_string();

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 5),
            session.status,
            DoneSessionOutputMode::Summary,
            None,
            None,
            None,
        );

        // Assert
        let prompt_line = lines
            .iter()
            .find(|line| line.to_string().trim_end().starts_with(" › "))
            .expect("expected user prompt line");
        assert_eq!(prompt_line.to_string().trim_end(), " › /model gemini");
        assert_eq!(
            prompt_line.width(),
            80 - usize::from(SessionOutput::output_horizontal_border_width())
        );
        assert_eq!(prompt_line.spans[0].style.fg, Some(style::palette::ACCENT));
        assert!(
            prompt_line.spans[0]
                .style
                .add_modifier
                .contains(Modifier::BOLD)
        );
    }

    #[test]
    fn test_output_lines_use_full_panel_width_without_vertical_borders() {
        // Arrange
        let mut session = session_fixture();
        session.output = "abcdef".to_string();

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 6, 5),
            session.status,
            DoneSessionOutputMode::Summary,
            None,
            None,
            None,
        );

        // Assert
        assert_eq!(
            lines.first().expect("expected output line").to_string(),
            "abcdef"
        );
    }

    #[test]
    fn test_output_horizontal_border_width_is_zero_without_vertical_borders() {
        // Arrange & Act
        let horizontal_border_width = SessionOutput::output_horizontal_border_width();
        let output_panel_borders = SessionOutput::output_panel_borders();

        // Assert
        assert_eq!(horizontal_border_width, 0);
        assert!(!output_panel_borders.intersects(Borders::LEFT));
        assert!(!output_panel_borders.intersects(Borders::RIGHT));
    }

    #[test]
    fn test_output_lines_appends_empty_line_when_done() {
        // Arrange
        let mut session = session_fixture();
        session.output = "some output".to_string();
        session.status = Status::Done;

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 5),
            session.status,
            DoneSessionOutputMode::Summary,
            None,
            None,
            None,
        );

        // Assert
        assert!(lines.last().expect("lines").to_string().is_empty());
        assert!(lines.len() >= 2);
    }

    #[test]
    fn test_output_lines_appends_empty_line_before_spinner() {
        // Arrange
        let mut session = session_fixture();
        session.output = "some output".to_string();
        session.status = Status::InProgress;

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 5),
            session.status,
            DoneSessionOutputMode::Summary,
            None,
            None,
            None,
        );

        // Assert
        assert!(lines.len() >= 3);
        let len = lines.len();
        assert!(lines[len - 2].to_string().is_empty());
        assert!(lines[len - 1].to_string().contains("Working..."));
    }

    #[test]
    fn test_output_text_with_spaced_user_input_adds_empty_line_before_and_after() {
        // Arrange
        let output = "assistant output\n › user prompt\nagent response";

        // Act
        let spaced = SessionOutput::output_text_with_spaced_user_input(output);

        // Assert
        assert_eq!(
            spaced,
            "assistant output\n\n › user prompt\n\nagent response"
        );
    }

    #[test]
    fn test_output_text_with_spaced_user_input_keeps_existing_empty_lines() {
        // Arrange
        let output = "assistant output\n\n › user prompt\n\nagent response";

        // Act
        let spaced = SessionOutput::output_text_with_spaced_user_input(output);

        // Assert
        assert_eq!(spaced, output);
    }

    #[test]
    fn test_output_text_with_spaced_user_input_keeps_multiline_user_prompt_together() {
        // Arrange
        let output = "assistant output\n › first line\nsecond line\n\nagent response";

        // Act
        let spaced = SessionOutput::output_text_with_spaced_user_input(output);

        // Assert
        assert_eq!(
            spaced,
            "assistant output\n\n › first line\nsecond line\n\nagent response"
        );
    }

    #[test]
    fn test_output_text_with_spaced_user_input_adds_question_group_spacing_for_clarifications() {
        // Arrange
        let output = "assistant output\n › Clarifications:\n   1. Q: Need target branch?\n      \
                      A: main\n   2. Q: Need tests?\n      A: yes\n\nagent response";

        // Act
        let spaced = SessionOutput::output_text_with_spaced_user_input(output);

        // Assert
        assert_eq!(
            spaced,
            "assistant output\n\n › Clarifications:\n   \n   1. Q: Need target branch?\n      A: \
             main\n   \n   2. Q: Need tests?\n      A: yes\n\nagent response"
        );
    }

    #[test]
    fn test_status_message_for_merging() {
        // Arrange & Act
        let message = SessionOutput::status_message(Status::Merging, None);

        // Assert
        assert_eq!(message, "Merging...");
    }

    #[test]
    fn test_status_message_for_queued() {
        // Arrange & Act
        let message = SessionOutput::status_message(Status::Queued, None);

        // Assert
        assert_eq!(message, "Waiting in merge queue...");
    }

    #[test]
    fn test_output_lines_use_generic_in_progress_loader() {
        // Arrange
        let mut session = session_fixture();
        session.output = "some output".to_string();
        session.status = Status::InProgress;

        // Act
        let lines = SessionOutput::output_lines(
            &session,
            Rect::new(0, 0, 80, 5),
            session.status,
            DoneSessionOutputMode::Summary,
            None,
            None,
            None,
        );
        let text = lines
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n");

        // Assert
        assert!(text.contains("Working..."));
    }

    #[test]
    fn test_status_message_for_in_progress_includes_progress_text() {
        // Arrange & Act
        let message =
            SessionOutput::status_message(Status::InProgress, Some("Inspecting changed files"));

        // Assert
        assert_eq!(message, "Working... Inspecting changed files");
    }

    #[test]
    fn test_builder_methods() {
        // Arrange
        let session = session_fixture();
        let active_progress = "Inspecting changed files";
        let review_status_message = "Preparing review...";
        let review_text = "Assisted review";

        // Act
        let output = SessionOutput::new(&session)
            .active_progress(active_progress)
            .done_session_output_mode(DoneSessionOutputMode::Output)
            .review_status_message(Some(review_status_message))
            .review_text(Some(review_text))
            .scroll_offset(10);

        // Assert
        assert_eq!(output.active_progress, Some(active_progress));
        assert_eq!(
            output.done_session_output_mode,
            DoneSessionOutputMode::Output
        );
        assert_eq!(output.review_status_message, Some(review_status_message));
        assert_eq!(output.review_text, Some(review_text));
        assert_eq!(output.scroll_offset, Some(10));
    }

    #[test]
    fn test_render_does_not_draw_status_title_in_output_border() {
        // Arrange
        let mut session = session_fixture();
        session.title = Some("Header Session".to_string());
        session.status = Status::Review;
        let output = SessionOutput::new(&session);
        let backend = ratatui::backend::TestBackend::new(80, 10);
        let mut terminal = ratatui::Terminal::new(backend).expect("failed to create terminal");

        // Act
        terminal
            .draw(|frame| {
                let area = frame.area();
                output.render(frame, area);
            })
            .expect("failed to draw session output");

        // Assert
        let text = buffer_text(terminal.backend().buffer());
        assert!(!text.contains("Review - Header Session"));
    }
}
