name: Presubmit

on:
  pull_request:
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  coverage:
    name: SonarQube
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Generate and publish coverage
        uses: $/.github/actions/run-coverage
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}

  e2e:
    name: End-to-end feature tests
    uses: $/.github/workflows/e2e.yml

  validate:
    name: Workspace checks
    uses: $/.github/workflows/workspace-validation.yml
    with:
      cargo-audit: true
      cargo-machete: true
      workspace-tests: true
    secrets:
      TRUNK_API_TOKEN: ${{ secrets.TRUNK_API_TOKEN }}
